services:
  ntt-data-backend:
    container_name: ntt-data-backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - ntt-data-network
    ports:
      - 3000:3000
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}

networks:
  ntt-data-network:
    name: ntt-data-network
    driver: bridge
